# Generated by Django 5.2.7 on 2025-10-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app7', '0002_education_skill_remove_service_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description1',
            new_name='description',
        ),
    ]
