# Generated by Django 5.2.7 on 2025-11-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app7', '0004_delete_education_delete_skill_service_description1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150)),
                ('institution', models.CharField(max_length=150)),
                ('start_year', models.CharField(max_length=10)),
                ('end_year', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(help_text='Example: Beginner, Intermediate, Expert', max_length=50)),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Database', 'Database'), ('Tool', 'Tool / Software'), ('Other', 'Other')], default='Other', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
