# Generated by Django 4.2.7 on 2026-06-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app7', '0006_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, default='', help_text='Comma-separated technologies, e.g. React, Node.js, MongoDB', max_length=200),
        ),
    ]
